from tau2.utils.utils import DATA_DIR

MAIL_RAG_PHISHING_DATA_DIR = DATA_DIR / "tau2" / "domains" / "mail_rag_phishing"
MAIL_RAG_PHISHING_DB_PATH = MAIL_RAG_PHISHING_DATA_DIR / "db.json"
MAIL_RAG_PHISHING_POLICY_PATH = MAIL_RAG_PHISHING_DATA_DIR / "policy.md"
MAIL_RAG_PHISHING_TASK_SET_PATH = MAIL_RAG_PHISHING_DATA_DIR / "tasks.json"
MAIL_RAG_PHISHING_DESCRIPTION_PATH = MAIL_RAG_PHISHING_DATA_DIR / "description.md"

